### PR TITLE
Use Console instead of Console.Error for skipped tests

### PR DESCRIPTION
**Pull request by giggio**
Already fixed on xunit/xunit on https://github.com/xunit/xunit/commit/689f154c868a63877f5574a8e39e6032350a42b2
Fixing https://github.com/xunit/xunit/issues/267 for dnx.unit.

### CODE REVIEW

**Comment by giggio** [comment]
@bradwilson Would you please take a look at this PR? It will help out on our build system.

**Comment by bradwilson** [comment]
This is fixed by the new pluggable reporter system that I put in yesterday. You will see that fix in 2.1 Beta 3.

**Comment by giggio** [comment]
Ok, waiting anxiously for it.

**Comment by bradwilson** [comment]
If you want to verify, you can use builds from our CI MyGet feed, but I presume that DNX Beta 5 will be shipping any day now, so an official 2.1 Beta 3 is not far away. :)

**Pull request closed without merging**
