### PR TITLE
React to DNX renames

### PR DESCRIPTION
**Pull request by victorhurdugaci**
The change covers the DNX renames here: https://github.com/aspnet/dnx/pull/2346
They also include the changes in https://github.com/xunit/dnx.xunit/pull/51

cc @bradwilson @anurse @davidfowl 

PS: dnx build 12290 is not yet on the myget/aspnetvnext. It is being produced right now but I hit some tests failures because xunit was referencing the old package names

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
@bradwilson without this change, no one can run tests with the latest dnx. I plan to upload a private build of `xunit.runner.dnx` to the `aspnetvnext` (https://www.myget.org/F/aspnetvnext/api/v2) feed in order to unblock people until you merge the PR. Afterwards, I'll remove it. 

Let me know what you think.

**Comment by bradwilson** [comment]
If your name is sure to be alphabetically earlier than my beta 5 name (f.e., you use `2.1.0-beta5-aspnet-*`, since we use `2.1.0-beta5-build*`) then it shouldn't be an issue for you to publish something on your feed.

**Comment by bradwilson** [comment]
So I'm trying to update to the latest DNX, and using beta7-12302, it appears that most of your renames haven't yet hit /F/aspnetvnext. The only thing that seems necessary is the LoadableAssemblies => Assemblies rename.

**Comment by bradwilson** [comment]
Although it compiles, it doesn't run:

```
System.InvalidOperationException: Unable to resolve project 'dnx.xunit' from D:\Dev\xunit\dnx.xunit
   at Microsoft.Dnx.Runtime.ApplicationHostContext..ctor(IServiceProvider hostServices, String projectDirectory, String packagesDirectory, String configuration, FrameworkName targetFramework, ICache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCacheDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation)
   at Microsoft.Dnx.Runtime.DefaultHost.Initialize(RuntimeOptions options, IServiceProvider hostServices)
   at Microsoft.Dnx.Runtime.DefaultHost..ctor(RuntimeOptions options, IServiceProvider hostServices)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

Are we in a broken state with /F/aspnetvnext right now?

**Comment by bradwilson** [comment]
I'm pushed a `beta7` branch if you want to take a look: https://github.com/xunit/dnx.xunit/tree/beta7

**Comment by anurse** [comment]
We're having some build issues right now and some things haven't reached aspnetvnext. Our bad, we'll ping back when things clear up a bit.

**Comment by victorhurdugaci** [comment]
Most renames are on aspnetvnext since dnx 12290. 
Brad, the changes in the beta7 branch look good.

**Comment by bradwilson** [comment]
@victorhurdugaci Except they don't compile.

**Comment by bradwilson** [comment]
These changes have been integrated. Thanks!

**Pull request closed without merging**
