### PR TITLE
Use new target framework monikers

### PR DESCRIPTION
**Pull request by geirsagberg**
From the breaking change in ASP.NET 5 RC 1: https://github.com/aspnet/Announcements/issues/98

### CODE REVIEW

**Comment by bradwilson** [comment]
This is not appropriate.

The DNX runner is an application, not a class library. It must target DNX.

**Comment by SharpNoiZy** [comment]
+1
The lib is currently not usable in fresh new created RC1 project.

**Comment by bradwilson** [comment]
It is if you follow the directions. http://xunit.github.io/docs/getting-started-dnx.html

**Comment by geirsagberg** [comment]
My bad:

> As of RC1, the Visual Studio tooling for class library projects will use the net451 and dotnet5.4 frameworks in your project.json file. Unit tests are a special kind of platform-specific class library, so you must use the dnx451 and dnxcore50 framework names when writing unit tests; otherwise, the xunit.runner.dnx dependency will cause package restore failures.

**Pull request closed without merging**
